networks:
  gaia_lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24

services:
  gaia_firewall:
    image: gaia_firewall
    container_name: gaia_firewall
    privileged: true
    ports:
      - "8080:80"
      - "2222:22"
    networks:
      gaia_lab_net:
        ipv4_address: 10.5.0.5
    command: sh -c "iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 10.5.0.10:80 && iptables -t nat -A PREROUTING -p tcp --dport 2222 -j DNAT --to-destination 10.5.0.20:2222 && iptables -t nat -A POSTROUTING -j MASQUERADE && tail -f /dev/null"

  honeypot_gaia:
    image: cowrie/cowrie:latest
    ports:
      - "2223:2222"
    container_name: honeypot_gaia
    networks:
      gaia_lab_net:
        ipv4_address: 10.5.0.20

  victima_apache:
    image: httpd:2.4-alpine
    container_name: victima_apache
    networks:
      gaia_lab_net:
        ipv4_address: 10.5.0.10
    volumes:
      - ./html:/usr/local/apache2/htdocs/
      - ./logs:/usr/local/apache2/logs/
    # Usamos una sintaxis de comando más robusta para Alpine
    command: >
      sh -c "
      echo 'ExtendedStatus On' > /usr/local/apache2/conf/extra/status.conf &&
      echo '<Location /server-status>' >> /usr/local/apache2/conf/extra/status.conf &&
      echo '    SetHandler server-status' >> /usr/local/apache2/conf/extra/status.conf &&
      echo '    Require all granted' >> /usr/local/apache2/conf/extra/status.conf &&
      echo '</Location>' >> /usr/local/apache2/conf/extra/status.conf &&
      sed -i 's|#Include conf/extra/httpd-info.conf|Include conf/extra/status.conf|' /usr/local/apache2/conf/httpd.conf &&
      httpd-foreground"

  gaia_antivirus:
    image: clamav/clamav:stable
    container_name: gaia_antivirus
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./html:/scandir:ro
    networks:
    - gaia_lab_net

  ids_sniffer:
    image: gaia_sniffer
    container_name: ids_sniffer
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./capturas_pcap:/capturas
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - victima_apache
