# Dockerfile.sniffer
FROM alpine:3.19

RUN apk add --no-cache tcpdump

CMD ["sh", "-c", "NAME=$(date +%Y-%m-%d_%H-%M-%S) && tcpdump -i any -w /capturas/$NAME.pcap"]
# CMD ["sh","-c", "apk add --no-cache tcpdump && NAME=$$(date +%Y-%m-%d_%H-%M-%S) && tcpdump -i any -w /capturas/$$NAME.pcap"]
