networks:
  gaia_lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24

services:
  gaia_firewall:
    image: alpine:3.19
    container_name: gaia_firewall
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    command: >
      sh -c "apk add --no-cache iptables &&
             iptables -P INPUT ACCEPT &&
             iptables -P FORWARD ACCEPT &&
             iptables -P OUTPUT ACCEPT &&
             tail -f /dev/null"
    networks:
      gaia_lab_net:
        ipv4_address: 10.5.0.5

  gaia_antivirus:
    image: clamav/clamav:latest
    container_name: gaia_antivirus
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./html:/scandir:ro
    networks:
      gaia_lab_net:

  victima_apache:
    image: httpd:2.4-alpine
    container_name: victima_apache
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./html:/usr/local/apache2/htdocs/:ro
    ports:
      - "8080:80"
    networks:
      gaia_lab_net:
        ipv4_address: 10.5.0.10

  honeypot_gaia:
    image: cowrie/cowrie:latest
    container_name: honeypot_gaia
    security_opt:
      - no-new-privileges:true
    ports:
      - "2222:2222"
    networks:
      gaia_lab_net:
        ipv4_address: 10.5.0.20

  ids_sniffer:
    image: alpine:3.19
    container_name: ids_sniffer
    network_mode: "host"
    volumes:
      - ./capturas_pcap:/capturas
      # Sincroniza la zona horaria con el host
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: >
      sh -c "apk add --no-cache tcpdump && 
             NAME=$$(date +%Y-%m-%d_%H-%M-%S) &&
             tcpdump -i any -w /capturas/$$NAME.pcap"
    depends_on:
      - victima_apache
