# Dockerfile.firewall
FROM alpine:3.19

RUN apk add --no-cache iptables

# Copiar script de configuración del firewall
COPY firewall-rules.sh /usr/local/bin/firewall-rules.sh
RUN chmod +x /usr/local/bin/firewall-rules.sh

CMD ["/usr/local/bin/firewall-rules.sh"]
